# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cimg/elixir:1.11
        environment:
          MIX_ENV: test
    working_directory: ~/spandex_datadog
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix format --check-formatted
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix test
